import { Sidebar } from "../sidebars/Sidebar"

export function Home() {
    return (
        <div className="flex min-h-screen bg-gray-100">
            <Sidebar />
            <main className="flex-1 ml-64 p-6 overflow-y-auto">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, numquam in! Nostrum quas, laborum ducimus ut nesciunt earum sed quasi amet nobis molestias vitae sint blanditiis, harum atque odio error.
                Hic, et blanditiis. A culpa ducimus alias harum? Vero totam illum cum quisquam, earum nemo, dolorem minus reprehenderit maiores at magni minima porro ratione laboriosam, eos sequi ducimus ad quasi?
                Aspernatur provident nemo repudiandae eius soluta, aperiam labore voluptatibus debitis sapiente obcaecati commodi, accusamus ut corporis qui necessitatibus atque incidunt asperiores repellendus molestias? Qui aliquid consectetur deserunt deleniti totam fuga.
                Aliquid minima, perferendis corporis praesentium qui exercitationem minus ratione labore quam, adipisci iste tempore ex consequatur tempora. Quaerat dignissimos quod et distinctio non nisi laudantium pariatur ratione, officiis voluptate labore?
                Nulla, sunt. Voluptatibus vero sunt beatae, magni id voluptatem amet dolore. Harum itaque est natus accusamus! Dolorum, at amet qui ducimus quis officiis dicta nulla quia neque voluptas magni saepe!
                Inventore ab laudantium molestias repudiandae deleniti quaerat facere ipsum alias culpa veritatis quo doloremque voluptas minus quas provident rerum magnam, dolorem, quidem accusantium omnis natus animi odio debitis. Impedit, aperiam.
                Minima odit minus alias qui delectus animi. Commodi itaque fugiat suscipit eligendi eos molestiae! Ullam, aspernatur ipsam ad esse possimus ipsum laborum accusantium eligendi soluta, fugit natus porro? Optio, blanditiis.
                Alias nulla, ducimus sint dicta reprehenderit ratione cum rerum neque, dolorem animi, sequi ullam! Dignissimos soluta inventore, aliquid impedit expedita distinctio voluptatem eaque mollitia sapiente, at quam sunt quasi nihil?
                Molestiae reprehenderit corporis placeat quod, corrupti rem commodi voluptates non. Harum molestias dolore temporibus, nemo dolorem repudiandae possimus perspiciatis inventore neque illo nihil nesciunt ipsam, dolores eos facere libero fugiat!
                Odit quos consequuntur aut cum exercitationem culpa pariatur. Pariatur alias ipsum, fugiat ea illum deleniti repellendus neque quaerat minima placeat veritatis odio veniam debitis assumenda dolorem aut quisquam, nisi excepturi!
                Quam, aut. Autem placeat aliquid illo consectetur veritatis quae inventore, numquam officia ducimus illum amet dolor quibusdam, doloribus commodi fugit pariatur iusto aspernatur quasi delectus! Explicabo obcaecati et iusto excepturi!
                Obcaecati, at. Corrupti ex ad harum suscipit nobis asperiores quisquam iusto maxime voluptas ipsam, non mollitia blanditiis molestias cum. Officiis nesciunt adipisci iusto atque consequuntur facilis voluptas reiciendis eos natus?
                Quae quia reiciendis quibusdam sit expedita possimus blanditiis eaque excepturi maiores magnam cupiditate reprehenderit provident, obcaecati, consequatur praesentium? Eos, deleniti laudantium asperiores voluptatibus ducimus quam modi tempore saepe iure ut?
                Sit, magnam? Dolorem, sit facere? Natus quibusdam quas numquam culpa atque expedita doloribus quis? Molestias laudantium ea, cupiditate repudiandae libero sint provident, labore autem temporibus atque culpa possimus quam voluptates.
                Aperiam, fuga facere! Quisquam quibusdam nostrum distinctio, impedit est beatae! Voluptatibus eos impedit obcaecati at pariatur ipsum ducimus, dolor assumenda maiores quia? Eius quisquam maiores doloribus repudiandae modi, tempora architecto?
                Omnis expedita numquam iusto maxime voluptatum, perspiciatis corrupti voluptate quas soluta animi. Debitis minus quae voluptas, asperiores sunt accusantium rem nam aut culpa consectetur, dolorem laudantium recusandae dolorum ducimus quaerat.
                Optio ullam officia laborum ducimus, ea, aut minima voluptatibus illo quo molestias cupiditate, adipisci sunt impedit aperiam est ipsum repellat quos commodi. Enim recusandae ipsa porro tenetur neque aperiam nulla.
                Facere ratione veritatis expedita magnam officiis quibusdam tenetur neque deleniti odit nam tempore quos corporis repudiandae, sequi necessitatibus minima eius perspiciatis doloremque rerum eum ipsa voluptatibus! Ea assumenda velit eos.
                Maiores eum, earum quod sed quis blanditiis ut soluta. Mollitia quia perferendis porro consequatur exercitationem repudiandae officia asperiores sint cumque quisquam similique laborum fugit atque maiores ullam saepe, tempora voluptas?
                Ipsam eaque veritatis natus hic, voluptas itaque. Nesciunt, molestias. Ratione iste fugit quos labore neque iusto porro veniam quas, laboriosam amet? Autem sit nulla incidunt delectus magni nihil porro eum!
                Distinctio beatae hic, consectetur similique minima quas tempore velit magnam magni doloribus rem a quibusdam ab possimus deleniti itaque iste provident harum iure optio amet, consequuntur fugit dolorem cumque. Commodi?
                Expedita dolorum nam totam. Reprehenderit, earum! Exercitationem beatae odio excepturi vero esse atque accusantium sunt iure autem iste possimus nostrum sed totam est cum pariatur tenetur, tempore quidem assumenda sit?
                Nemo ducimus omnis eveniet architecto quidem, eaque fugit, harum minus necessitatibus culpa sequi nesciunt, et dolorem? Id explicabo molestiae deleniti quisquam odio iste magni, rerum consequatur, voluptatem, non voluptatibus quasi?
                Eligendi quis minus suscipit similique! Praesentium dolorum id vel, ipsa asperiores voluptatem magni? Ut laboriosam quis, dolorem voluptas itaque, nobis dignissimos expedita, sequi a optio accusantium sint minus. Odit, excepturi!
                Culpa odio nam eius autem ipsum obcaecati libero eligendi error. Magnam, quisquam delectus nihil quam animi cum, obcaecati dolor soluta, illo repellendus ducimus. Ad tempore maiores, unde magnam assumenda eaque.
                Mollitia optio, vero rem aliquam labore sit voluptas reprehenderit amet consequatur officiis praesentium fuga autem odio earum! Enim quod pariatur nulla vitae eaque, unde cupiditate animi illum voluptates praesentium qui!
                Nemo quasi tenetur itaque fuga sequi illum sed necessitatibus. Cum expedita vitae quae corrupti, nemo deleniti porro quaerat minima quasi, qui facere natus! Dolore id explicabo eveniet at reiciendis ab?
                Aperiam hic dolorem animi, officia explicabo ipsam voluptate voluptas molestiae laborum debitis obcaecati voluptatem tempora aliquam adipisci exercitationem incidunt! Deleniti a tempora voluptatibus tempore deserunt atque rem exercitationem expedita officiis!
                Expedita explicabo voluptatum facere natus quibusdam doloremque, recusandae amet fugiat vero harum illo excepturi quae? Aperiam magnam quibusdam eos perspiciatis accusamus reiciendis, velit praesentium consectetur, blanditiis iusto sequi accusantium adipisci?
                Dolores vel, eum recusandae, tenetur quaerat velit veritatis quisquam eaque earum saepe provident, nemo explicabo rerum incidunt nulla nesciunt ipsam corrupti excepturi. Perferendis minus corporis alias quo odio iusto at.
                Sequi, facere hic tenetur minus repellendus rerum atque accusamus blanditiis non? Tenetur commodi nemo nesciunt exercitationem! Pariatur, natus enim facere impedit necessitatibus, dolorem culpa reprehenderit deserunt voluptas nesciunt doloribus alias.
                Enim quasi quia sit sequi ipsum ad cupiditate adipisci ipsam distinctio debitis vero quo eius, harum ullam esse eum repellendus delectus illo, velit voluptas? Accusamus quae magnam impedit facilis ullam.
                Sequi voluptate ratione necessitatibus illo assumenda qui earum suscipit nulla ipsa odit magnam asperiores aut sapiente voluptas labore et minus, perferendis hic aperiam, error architecto voluptates nobis enim. Repellendus, libero?
                Quos cum illo obcaecati fuga expedita. Quis, voluptate exercitationem totam beatae eaque quia quae rem laborum inventore, illum esse? Perspiciatis eligendi quasi velit voluptate nemo laborum cum minus mollitia id.
                Doloremque, dignissimos culpa sit harum ex quia aliquam quo tenetur optio aliquid dolore itaque non ut magni totam provident natus laboriosam beatae velit quod neque voluptas porro illum! Dignissimos, rerum?
                Repellendus maxime, odit molestias, quod sint temporibus quasi et molestiae culpa harum beatae vitae, accusamus sequi maiores autem nostrum tempore reiciendis doloremque! Ipsam perferendis ea ullam iste. Velit, enim sint.
                Expedita voluptas voluptates porro beatae, placeat labore commodi error nulla corporis. Est numquam pariatur nesciunt provident illum! Vero veniam pariatur amet, optio incidunt cum quam, blanditiis itaque animi cumque provident.
                Accusantium adipisci, ut iste nulla vitae nam amet ipsum sit. Dolorem eveniet cum non natus optio quia neque. A delectus maiores atque odio quod blanditiis iure similique expedita sint aut.
                Iste reprehenderit sit ut tenetur eligendi a maiores at facilis commodi. Libero voluptatem sunt quae labore dolores, vero, deleniti dolor ipsa delectus doloremque explicabo minus ex, corrupti distinctio iure expedita.
                Nisi ipsa doloribus velit exercitationem, facere porro veniam rerum enim, vel est voluptatum architecto error illum provident ea soluta pariatur vitae dicta? Esse itaque aut natus quod modi culpa minus!
                Inventore quae similique perferendis sunt laudantium fuga fugit eos nulla, est perspiciatis sint aut et autem, nostrum modi? Excepturi, necessitatibus! Et ipsum iste, voluptas dolor iure quas nulla cupiditate ipsa.
                Mollitia, ipsum. Eveniet, harum labore ea perferendis eligendi sunt illum inventore! Dolore ex, voluptatum, in voluptates accusantium at quis, aspernatur ratione molestiae labore dolorum consequuntur rerum perspiciatis minus incidunt provident?
                Dicta ex eaque illum, facere illo saepe reprehenderit veniam eos porro sit. Corporis ipsa quae placeat porro beatae numquam? Fugiat beatae maxime voluptatibus? Sequi qui commodi culpa magni repellat quia.
                Nulla veniam id magni minima nesciunt nemo rem illum sapiente vero architecto aliquam voluptatum eaque sint ducimus est, fugit dolorem fugiat molestias soluta sed voluptatem in? Unde totam rerum officia!
                Et esse consequuntur ullam optio a excepturi, consequatur saepe labore neque ipsam, magni eum praesentium assumenda accusamus dolores itaque numquam repudiandae quia debitis non sed quod! Cumque sint atque recusandae!
                Nobis voluptate, repudiandae reiciendis sint magni explicabo dicta? Adipisci aperiam delectus distinctio est cupiditate laudantium dicta deserunt, velit eaque. Aliquid repellat ex dignissimos necessitatibus. Quam, veritatis eligendi. Magni, expedita temporibus.
                Et voluptatibus, excepturi ut porro corrupti, cumque architecto illo nam praesentium, quas molestias totam temporibus hic eveniet recusandae quia dolorem nemo magni quo at veritatis aliquam. Quo assumenda doloremque adipisci?
                Veniam ea repellendus provident magni modi culpa. Optio adipisci voluptas dolor rerum! Expedita culpa enim iste cupiditate. Adipisci hic illum officia quam accusamus ipsum tenetur incidunt. Eaque, perferendis! Iusto, voluptas.
                Omnis, quod itaque eos repudiandae nihil ab laborum natus eius labore totam magni temporibus id fuga veniam nesciunt, ducimus, non optio! Vitae modi in ex eligendi. Inventore culpa commodi aliquam?
                Perferendis dolorum nulla veritatis placeat quibusdam quisquam, quaerat ratione nihil qui, eius quod deserunt voluptates error porro provident nemo maiores officia hic omnis architecto libero itaque molestiae ipsum corrupti! Voluptas.
            </main>
        </div>
    )
}